export const LOAD_QUESTIONS_START = 'LOAD_QUESTIONS_START';
export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTIONS_FAILURE = 'LOAD_QUESTIONS_FAILURE';

export const LOAD_QUESTION_DATA_START = 'LOAD_QUESTION_DATA_START';
export const LOAD_QUESTION_DATA_SUCCESS = 'LOAD_QUESTION_DATA_SUCCESS';
export const LOAD_QUESTION_DATA_FAILURE = 'LOAD_QUESTION_DATA_FAILURE';

export const ADD_NEW_RESULT = 'ADD_NEW_RESULT';
export const CLEAR_RESULTS = 'CLEAR_RESULTS';